exclude: '\.idea/|\.vscode/|dev/'
minimum_pre_commit_version: 3.6.0
default_language_version:
  python: python3.11
  node: "20.10.0"
repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude_types: [tsv]
  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff-format
        args: ["--preview"]
        types_or: [python, pyi]
      - id: ruff
        name: ruff-isort
        args: ["--select", "I", "--fix"]
        types_or: [python, pyi]
      - id: ruff
        types_or: [python, pyi]
        args: ["--select", "W,E", "--output-format", "concise"]
  # pyright
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.393
    hooks:
      - id: pyright
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [
            "--disable",
            "MD013", # Line length
            "MD033", # Inline HTML
            "--", # otherwise files are interpreted as args
          ]
  # shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"]
  - repo: https://github.com/randolf-scholz/latex-hooks.git
    rev: v0.0.2
    hooks:
      - id: check-separator-length-88
      - id: latex-avoid-def
      - id: latex-avoid-let
      - id: latex-avoid-newcommand
      - id: latex-avoid-legacy-options
      - id: latex-avoid-double-dollar
      - id: latex-avoid-obsolete-packages
      - id: chktex
      - id: lacheck
        exclude: tests/
